version: '3.2'

services:

  cstrike-gameserver:
    image: hlds
    env_file: .env
    ulimits:
      core:
        soft: 1073741824 # 1GB
        hard: 1073741824 # 1GB
    ports:
      - ${PORT}:${PORT}/udp
    stdin_open: true
    tty: true
    build:
      context: ./bullseye
      args:
        - REHLDS=latest
        - REGAMEDLL=latest
        - METAMOD=latest
        - AMXMODX=1.10.0-git5466
    command: [
        "-debug",
        "-game cstrike",
        "-ip 0.0.0.0",
        "-port ${PORT}",
        "+map ${MAP}",
        "-maxplayers ${MAXPLAYERS}",

        # Debug 
        # "+log on",
        # "+mp_logecho 1",
        # "-condebug",
        # "+localinfo mm_debug 3",
    ]

